languageCode = "fr"
name = "Avant Conseils"
title = "Avant-conseils"
description =   "Avant conseils, L'agence digitale, liégeoise et écoresponsable qui vous accompagne dans votre développement numérique"
theme = ["avant", "matomo"]
baseURL = "https://avantconseils.be"

[params]
    author = "Anthony.E"
    authorImage = "/images/avatar.jpg"


[[menu.main]]
  name = "Nos services"
  url = "#services"
  weight = 1


[[menu.main]]
  name = "Nos engagements"
  url = "#engagement"
  weight = 2

  [[menu.main]]
  name = "contact"
  url = "#contact"
  weight = 3

  [[menu.footer]]
  name = "termes et conditions"
  url = "/termes"

[[menu.footer]]
  name = "politique de confidentialité"
  url = "/politique"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

  enableRobotsTXT = true

