languageCode = "fr"
name = "Avant Conseils"
title = "Avant-conseils"
description = "My site description"
theme = ["avant", "matomo"]
googleAnalytics = "UA-123-45"

[params]
    author = "Anthony.E"
    authorImage = "/images/avatar.jpg"


[[menu.main]]
  name = "Nos services"
  url = "#services"
  weight = 1


[[menu.main]]
  name = "Nos engagements"
  url = "#engagement"
  weight = 2

  [[menu.main]]
  name = "contact"
  url = "#contact"
  weight = 3

  [[menu.footer]]
  name = "termes et conditions"
  url = "/termes"

[[menu.footer]]
  name = "politique de confidentialité"
  url = "/politique"

